apiVersion: v1
kind: Service
metadata:
  name: {{ include "nessus.fullname" . }}
  namespace: nessus
  labels:
    {{- include "nessus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8834
      protocol: TCP
      name: https
  selector:
    {{- include "nessus.selectorLabels" . | nindent 4 }}
