name: Build & push base images
on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    paths:
      - 'oci/base/alpine-glibc/Dockerfile'
      - 'oci/base/alpine-awscli/Dockerfile'
  workflow_dispatch:
    branches:
      - main

jobs:
  alpine:
    runs-on: ubuntu-latest
    name: Build alpine base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push alpine with custom ca image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: './oci/base/alpine'
          build_file: 'Dockerfile'
          image: base/alpine
          tag: latest
          cache: true
          cache_registry: cache

  debian:
    runs-on: ubuntu-latest
    name: Build debian base image
    steps:
      - uses: actions/checkout@master

      - name: 'Artifact: build && push alpine with custom ca image'
        uses: aevea/action-kaniko@master
        with:
          registry: artifact.onwalk.net
          username: admin 
          password: ${{ secrets.HELM_REPO_PASSWORD }}
          path: './oci/base/debian'
          build_file: 'Dockerfile' 
          image: base/debian
          tag: latest
          cache: true
          cache_registry: cache

