name: BUILD Chart

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    paths:
      - 'charts'
      - '.github/workflows/charts.yaml'
    brnches:
      - main
  workflow_dispatch:
    branches: [ 'main' ]

env:
  REPO_URL: https://github.com/svc-design/NessusKaliPod.git 
  REPO_BRANCH: main
  DEBIAN_FRONTEND: noninteractive
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}

    - name: Initialization environment
      shell: bash
      run: |
        sudo apt update
        sudo apt install git -y
        sudo timedatectl set-timezone "$TZ"
        sudo curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm plugin install https://github.com/chartmuseum/helm-push.git

    - name: Clone Source
      shell: bash
      run: |
        git clone $REPO_URL -b $REPO_BRANCH

    - name: Build and Push chart
      shell: bash
      run: |
        helm repo add sync https://charts.onwalk.net
        helm repo up
        cd ${GITHUB_WORKSPACE}                                                          && \
        helm cm-push -u admin -p "${{ secrets.HELM_REPO_PASSWORD }}" charts/kali2/ sync && \
        helm cm-push -u admin -p "${{ secrets.HELM_REPO_PASSWORD }}" charts/nessus/ sync
