name: BUILD Chart

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  push:
    paths:
      - 'charts'
      - '.github/workflows/charts.yaml'
    brnches:
      - main
  workflow_dispatch:
    branches: [ 'main' ]

env:
  REPO_URL: https://github.com/svc-design/NessusKaliPod.git 
  REPO_BRANCH: main
  TZ: Asia/Shanghai
  TAG: 0.1.4

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
        REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install git -y
        sudo timedatectl set-timezone "$TZ"
        sudo curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        helm plugin install https://github.com/chartmuseum/helm-push.git
        echo "$REPO_PASSWORD" | helm repo add sync --username=admin --password-stdin https://artifact.onwalk.net/chartrepo/public/
        helm repo up

    - name: Clone Source
      shell: bash
      run: |
        git clone $REPO_URL -b $REPO_BRANCH

    - name: Build and Push chart
      shell: bash
      run: |
        cd ${GITHUB_WORKSPACE}/charts/kali2/ && rm *.tgz -f && helm package ./ && ls *.tgz && helm cm-push observableserver-${TAG}.tgz sync
        cd ${GITHUB_WORKSPACE}/charts/nessus/ && rm *.tgz -f && helm package ./ && ls *.tgz && helm cm-push observableserver-${TAG}.tgz sync
