name: Sync Images

on:
  pull_request:
  push:
    paths:
      - '.github/workflows/sync-images.yaml'
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  sync-terraform-images:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
      with:
        ref: ${{ github.head_ref }}

    - name: Initialization environment
      env:
        REPO_PASSWORD: ${{ secrets.HELM_REPO_PASSWORD }}
      shell: bash
      run: |
        sudo apt update
        sudo apt install git -y
        sudo timedatectl set-timezone "$TZ"
        echo "$REPO_PASSWORD" | docker login --username=admin --password-stdin artifact.onwalk.net

    - name: Sync terraform images
      shell: bash
      run: |
        docker pull hashicorp/terraform:latest 
        docker tag hashicorp/terraform:latest artifact.onwalk.net/devops/terraform:latest
        docker push artifact.onwalk.net/devops/terraform:latest
